baseurl = "/"
languageCode = "en-us"
title = "Sophie's Cabin"
theme = "hugo-lithium"
googleAnalytics = "G-ERXJ692Y8L"
disqusShortname = "xshen_sophie"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Publication"
    url = "/Publication/"
[[menu.main]]
    name = "Activities"
    url = "/Activities/"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/xshen1314/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/XSophie"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/XsSophie"
    

[params]
    description = "A website built through Hugo and blogdow. Focus on building up the data analysis skills and personal growth."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml","markdown"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "Sophie.jpg"

    [params.logo]
    url = "Sophie.jpg"
    width = 50
    height = 50
    alt = "Sophie.jpg"

